use windows::Win32::UI::Input::KeyboardAndMouse::*;

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Key {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Space,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
}

impl Key {
    pub fn to_virtual_key(&self) -> u16 {
        match self {
            Self::A => VK_A,
            Self::B => VK_B,
            Self::C => VK_C,
            Self::D => VK_D,
            Self::E => VK_E,
            Self::F => VK_F,
            Self::G => VK_G,
            Self::H => VK_H,
            Self::I => VK_I,
            Self::J => VK_J,
            Self::K => VK_K,
            Self::L => VK_L,
            Self::M => VK_M,
            Self::N => VK_N,
            Self::O => VK_O,
            Self::P => VK_P,
            Self::Q => VK_Q,
            Self::R => VK_R,
            Self::S => VK_S,
            Self::T => VK_T,
            Self::U => VK_U,
            Self::V => VK_V,
            Self::W => VK_W,
            Self::X => VK_X,
            Self::Y => VK_Y,
            Self::Z => VK_Z,
            Self::Space => VK_SPACE,
            Self::Num0 => VK_0,
            Self::Num1 => VK_1,
            Self::Num2 => VK_2,
            Self::Num3 => VK_3,
            Self::Num4 => VK_4,
            Self::Num5 => VK_5,
            Self::Num6 => VK_6,
            Self::Num7 => VK_7,
            Self::Num8 => VK_8,
            Self::Num9 => VK_9,
        }
    }
}
